/*
  # Seed Tools Data

  Inserts 40 representative tools across the main categories.
  Uses slugs from the categories table to resolve category_id via subquery.
*/

INSERT INTO tools (name, slug, tagline, description, website, logo_url, category_id, pricing, pricing_details, tags, rating, review_count, upvotes, is_featured, is_trending, difficulty_level) VALUES

-- AI & Machine Learning
('ChatGPT', 'chatgpt', 'The most popular AI chatbot in the world', 'ChatGPT is an AI-powered chatbot developed by OpenAI that can engage in conversations, answer questions, write content, debug code, and much more.', 'https://chat.openai.com', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'ai-chatbots'), 'freemium', 'Free tier available. ChatGPT Plus at $20/month.', ARRAY['chatbot','openai','gpt-4','text generation'], 4.8, 12400, 9800, true, true, 'beginner'),

('Claude', 'claude', 'Anthropic''s thoughtful AI assistant', 'Claude is a next-generation AI assistant built by Anthropic, designed to be helpful, harmless, and honest. Great for writing, analysis, and coding.', 'https://claude.ai', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'ai-chatbots'), 'freemium', 'Free tier available. Claude Pro at $20/month.', ARRAY['chatbot','anthropic','writing','analysis'], 4.7, 5200, 7100, true, true, 'beginner'),

('Gemini', 'gemini', 'Google''s multimodal AI assistant', 'Gemini is Google''s most capable AI model, able to understand and generate text, images, audio, and code. Integrated across Google products.', 'https://gemini.google.com', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'ai-chatbots'), 'freemium', 'Free with Google account. Gemini Advanced available.', ARRAY['google','multimodal','chatbot','productivity'], 4.5, 3800, 5400, true, false, 'beginner'),

('Perplexity AI', 'perplexity-ai', 'AI-powered answer engine with real-time web search', 'Perplexity AI is a conversational search engine that answers questions with real-time information sourced from the web, complete with citations.', 'https://perplexity.ai', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'ai-chatbots'), 'freemium', 'Free tier. Pro at $20/month.', ARRAY['search','research','web','citations'], 4.6, 2900, 4200, false, true, 'beginner'),

-- Image Generation
('Midjourney', 'midjourney', 'AI art generator that produces stunning imagery', 'Midjourney is an AI image generation tool that creates high-quality, artistic images from text prompts via Discord. Known for its exceptional aesthetic quality.', 'https://midjourney.com', 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'image-generation'), 'paid', 'Basic plan from $10/month. Standard $30/month. Pro $60/month.', ARRAY['image generation','art','discord','creative'], 4.9, 18700, 14200, true, true, 'intermediate'),

('DALL-E 3', 'dalle-3', 'OpenAI''s most capable image generation model', 'DALL-E 3 is OpenAI''s latest image generation model, integrated into ChatGPT. It excels at following detailed prompts and creating realistic images.', 'https://openai.com/dall-e-3', 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'image-generation'), 'freemium', 'Included with ChatGPT Plus subscription ($20/month).', ARRAY['image generation','openai','realistic','creative'], 4.6, 7400, 8900, true, false, 'beginner'),

('Stable Diffusion', 'stable-diffusion', 'Open-source AI image generation model', 'Stable Diffusion is a powerful open-source text-to-image AI model. Available for free self-hosting or via commercial platforms with extensive customization options.', 'https://stability.ai', 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'image-generation'), 'free', 'Open source and free. Cloud platforms vary.', ARRAY['open source','image generation','self-hosted','customizable'], 4.5, 9200, 11000, false, false, 'advanced'),

('Adobe Firefly', 'adobe-firefly', 'Adobe''s generative AI for creative professionals', 'Adobe Firefly is a family of creative generative AI models integrated into Adobe Creative Cloud. Designed for safe commercial use with content credentials.', 'https://firefly.adobe.com', 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'image-generation'), 'freemium', 'Limited free credits. Adobe CC subscription required for full access.', ARRAY['adobe','creative','commercial safe','design'], 4.4, 4100, 5600, false, true, 'intermediate'),

-- Video Generation
('Sora', 'sora', 'OpenAI''s groundbreaking text-to-video model', 'Sora is OpenAI''s AI model that can generate realistic and imaginative video scenes from text instructions. It can create videos up to a minute long.', 'https://openai.com/sora', 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'video-generation'), 'paid', 'Available via ChatGPT Pro subscription.', ARRAY['video generation','openai','text-to-video','creative'], 4.7, 3200, 6800, true, true, 'intermediate'),

('Runway ML', 'runway-ml', 'Professional AI video generation and editing', 'Runway is a creative AI platform providing tools for video generation, editing, and special effects. Used by filmmakers and content creators worldwide.', 'https://runwayml.com', 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'video-generation'), 'freemium', 'Free trial. Standard from $12/month. Pro $28/month.', ARRAY['video','editing','film','creative'], 4.5, 2800, 4100, true, false, 'intermediate'),

('HeyGen', 'heygen', 'Create AI videos with realistic avatars', 'HeyGen lets you create professional AI videos using digital avatars, text-to-speech, and video translation. Perfect for marketing and corporate communications.', 'https://heygen.com', 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'video-generation'), 'freemium', 'Free trial. Creator plan from $29/month.', ARRAY['avatar','video','marketing','translation'], 4.3, 1900, 2700, false, true, 'beginner'),

-- Code Generation
('GitHub Copilot', 'github-copilot', 'AI pair programmer for developers', 'GitHub Copilot is an AI-powered code completion tool that helps developers write code faster. It suggests whole lines or blocks of code as you type.', 'https://github.com/features/copilot', 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'code-generation'), 'paid', 'Individual: $10/month. Business: $19/user/month.', ARRAY['coding','github','autocomplete','developer'], 4.7, 14800, 12100, true, true, 'intermediate'),

('Cursor', 'cursor', 'The AI-first code editor', 'Cursor is a code editor built for pair-programming with AI. It features deep codebase understanding, natural language code edits, and multi-file editing.', 'https://cursor.sh', 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'code-generation'), 'freemium', 'Free tier. Pro at $20/month.', ARRAY['editor','coding','ai','developer'], 4.8, 6700, 9400, true, true, 'intermediate'),

('v0 by Vercel', 'v0-vercel', 'Generate UI components with AI', 'v0 is a generative UI tool from Vercel that creates React and Tailwind CSS components from text descriptions. Ideal for rapid prototyping.', 'https://v0.dev', 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'code-generation'), 'freemium', 'Free credits. Pro subscription available.', ARRAY['ui','react','tailwind','frontend'], 4.6, 3400, 5800, true, true, 'beginner'),

('Bolt.new', 'bolt-new', 'Build and deploy full-stack apps with AI', 'Bolt.new is an AI-powered full-stack development environment. Describe your app and Bolt builds, runs, and deploys it directly in the browser.', 'https://bolt.new', 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'code-generation'), 'freemium', 'Free credits available. Subscription plans available.', ARRAY['fullstack','deployment','no-code','app builder'], 4.7, 2900, 7200, true, true, 'beginner'),

-- No-Code Tools
('Bubble', 'bubble', 'Build web apps without code', 'Bubble is the leading no-code platform for building web applications. Create complex, data-driven apps with a visual drag-and-drop editor, no coding required.', 'https://bubble.io', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'no-code-tools'), 'freemium', 'Free tier. Starter $29/month. Growth $119/month.', ARRAY['no-code','web app','database','automation'], 4.5, 8900, 7600, true, false, 'beginner'),

('Webflow', 'webflow', 'Professional website builder with CMS', 'Webflow is a powerful no-code website builder that gives designers full control over HTML, CSS, and JavaScript through a visual interface.', 'https://webflow.com', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'no-code-tools'), 'freemium', 'Free starter. Basic from $14/month. CMS from $23/month.', ARRAY['website','cms','design','hosting'], 4.6, 11200, 9800, true, false, 'intermediate'),

('Make (Integromat)', 'make', 'Visual automation platform for complex workflows', 'Make (formerly Integromat) is a powerful visual automation platform that connects apps and services to automate workflows without code.', 'https://make.com', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'no-code-tools'), 'freemium', 'Free plan. Core from $9/month.', ARRAY['automation','integration','workflow','zapier alternative'], 4.6, 6300, 5400, false, false, 'intermediate'),

('n8n', 'n8n', 'Open-source workflow automation tool', 'n8n is a free, open-source workflow automation tool that allows you to automate tasks and connect apps. Self-hostable with 400+ integrations.', 'https://n8n.io', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'no-code-tools'), 'freemium', 'Free self-hosted. Cloud from $24/month.', ARRAY['automation','open source','self-hosted','integration'], 4.7, 4800, 6200, false, true, 'intermediate'),

-- Writing & Copy
('Copy.ai', 'copy-ai', 'AI writing assistant for marketing copy', 'Copy.ai is an AI-powered writing tool that helps marketers and businesses create compelling copy for ads, emails, social media, and more.', 'https://copy.ai', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'writing'), 'freemium', 'Free 2,000 words/month. Pro $49/month.', ARRAY['copywriting','marketing','content','email'], 4.4, 5600, 4300, false, false, 'beginner'),

('Jasper', 'jasper', 'Enterprise AI content platform', 'Jasper is an AI content platform designed for marketing teams. It helps create on-brand content at scale with brand voice features and templates.', 'https://jasper.ai', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'writing'), 'paid', 'Creator plan $39/month. Teams $99/month.', ARRAY['content marketing','brand voice','seo','enterprise'], 4.3, 7200, 4800, true, false, 'beginner'),

('Grammarly', 'grammarly', 'AI writing assistant for grammar and style', 'Grammarly is an AI-powered writing assistant that checks grammar, spelling, style, and tone. Available as a browser extension and standalone app.', 'https://grammarly.com', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'writing'), 'freemium', 'Free basic. Premium $12/month. Business $15/user/month.', ARRAY['grammar','writing','editing','proofreading'], 4.6, 19800, 15600, true, false, 'beginner'),

-- Design & Creative
('Canva', 'canva', 'Design anything with AI-powered tools', 'Canva is a versatile design platform with thousands of templates and AI-powered features for creating social media graphics, presentations, and more.', 'https://canva.com', 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'design'), 'freemium', 'Free forever. Pro $12.99/month. Teams $14.99/user/month.', ARRAY['design','templates','presentations','social media'], 4.7, 23400, 19800, true, false, 'beginner'),

('Figma', 'figma', 'Collaborative design tool for teams', 'Figma is a browser-based UI design tool with real-time collaboration. Now featuring AI-powered design tools for faster prototyping.', 'https://figma.com', 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'design'), 'freemium', 'Free starter. Professional $12/editor/month.', ARRAY['ui design','prototyping','collaboration','ux'], 4.8, 17600, 16400, true, false, 'intermediate'),

-- Productivity
('Notion AI', 'notion-ai', 'AI assistant built into your workspace', 'Notion AI is an intelligent writing and summarization assistant built directly into Notion. Draft, summarize, translate, and brainstorm without leaving your workspace.', 'https://notion.so/product/ai', 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'productivity'), 'freemium', 'Notion AI add-on $10/member/month.', ARRAY['productivity','notes','writing','workspace'], 4.5, 8900, 7200, true, false, 'beginner'),

('Otter.ai', 'otter-ai', 'AI meeting transcription and notes', 'Otter.ai provides real-time meeting transcription, automated summaries, and action items. Integrates with Zoom, Google Meet, and Microsoft Teams.', 'https://otter.ai', 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'productivity'), 'freemium', 'Free 300 min/month. Pro $8.33/month.', ARRAY['transcription','meetings','notes','zoom'], 4.4, 6100, 4800, false, false, 'beginner'),

-- Social Media
('Buffer', 'buffer', 'Social media scheduling with AI assist', 'Buffer is a social media management platform that helps you schedule posts, analyze performance, and engage your audience across multiple channels.', 'https://buffer.com', 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'social-media'), 'freemium', 'Free 3 channels. Essentials $6/channel/month.', ARRAY['social media','scheduling','analytics','marketing'], 4.4, 7800, 5900, false, false, 'beginner'),

('Hootsuite', 'hootsuite', 'All-in-one social media management', 'Hootsuite is a social media management platform for scheduling posts, monitoring conversations, and measuring ROI across all major social networks.', 'https://hootsuite.com', 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'social-media'), 'paid', 'Professional $99/month. Team $249/month.', ARRAY['social media','scheduling','analytics','enterprise'], 4.2, 9400, 5200, false, false, 'intermediate'),

-- Voice & Audio
('ElevenLabs', 'elevenlabs', 'Ultra-realistic AI voice generation', 'ElevenLabs offers the most realistic AI voice synthesis available. Create custom voice clones, narrations, and multilingual content with natural-sounding voices.', 'https://elevenlabs.io', 'https://images.pexels.com/photos/3756766/pexels-photo-3756766.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'music-audio'), 'freemium', 'Free 10,000 chars/month. Starter $5/month. Creator $22/month.', ARRAY['voice','tts','cloning','podcast'], 4.8, 8200, 9600, true, true, 'beginner'),

('Suno', 'suno', 'Create music with AI from text prompts', 'Suno is an AI music generation tool that creates full songs with vocals and instruments from simple text descriptions. No musical experience required.', 'https://suno.com', 'https://images.pexels.com/photos/3756766/pexels-photo-3756766.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'music-audio'), 'freemium', 'Free 50 credits/day. Pro $8/month.', ARRAY['music','ai generation','songs','creative'], 4.6, 4300, 6700, false, true, 'beginner'),

-- Research
('Elicit', 'elicit', 'AI research assistant for literature review', 'Elicit is an AI research assistant that helps you find and analyze academic papers. It can extract key information, summarize findings, and identify trends.', 'https://elicit.com', 'https://images.pexels.com/photos/5473955/pexels-photo-5473955.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'research'), 'freemium', 'Free tier. Plus $10/month.', ARRAY['research','papers','academic','literature'], 4.5, 2800, 3400, false, false, 'intermediate'),

('Consensus', 'consensus', 'Search the science with AI', 'Consensus is an AI-powered search engine for scientific research. It finds consensus in peer-reviewed literature and explains complex topics simply.', 'https://consensus.app', 'https://images.pexels.com/photos/5473955/pexels-photo-5473955.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'research'), 'freemium', 'Free tier. Premium $8.99/month.', ARRAY['science','research','papers','evidence'], 4.4, 1900, 2600, false, false, 'beginner'),

-- Customer Support
('Intercom', 'intercom', 'AI-powered customer messaging platform', 'Intercom is a customer communications platform with a powerful AI chatbot (Fin) that resolves up to 50% of support questions automatically.', 'https://intercom.com', 'https://images.pexels.com/photos/7654586/pexels-photo-7654586.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'customer-support'), 'paid', 'Starter $74/month. Pro custom pricing.', ARRAY['customer support','chatbot','crm','messaging'], 4.4, 6700, 4400, false, false, 'intermediate'),

-- Sales & CRM
('HubSpot AI', 'hubspot-ai', 'CRM with built-in AI tools', 'HubSpot is a comprehensive CRM platform with AI-powered features for sales, marketing, and customer service. Includes AI content creation and deal forecasting.', 'https://hubspot.com', 'https://images.pexels.com/photos/7654586/pexels-photo-7654586.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'sales'), 'freemium', 'Free CRM. Starter $20/month. Professional $890/month.', ARRAY['crm','sales','marketing','email'], 4.5, 11400, 7800, true, false, 'intermediate'),

-- Education
('Khan Academy Khanmigo', 'khanmigo', 'AI tutor for students and teachers', 'Khanmigo is Khan Academy''s AI tutor powered by GPT-4. It guides students through problems using the Socratic method rather than giving answers directly.', 'https://khanacademy.org/khan-labs', 'https://images.pexels.com/photos/4145153/pexels-photo-4145153.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'education'), 'paid', '$4/month for students. Free for teachers in some regions.', ARRAY['education','tutoring','math','socratic'], 4.4, 3200, 4100, false, false, 'beginner'),

('Duolingo Max', 'duolingo-max', 'AI-powered language learning', 'Duolingo Max uses GPT-4 to power Explain My Answer and Roleplay features, giving learners personalized AI conversation practice.', 'https://duolingo.com', 'https://images.pexels.com/photos/4145153/pexels-photo-4145153.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'education'), 'freemium', 'Free tier. Plus $6.99/month. Max $13.99/month.', ARRAY['language learning','ai tutor','conversation','gamification'], 4.6, 8900, 7400, true, false, 'beginner'),

-- Finance
('YNAB', 'ynab', 'AI-enhanced personal budgeting', 'You Need A Budget (YNAB) is a personal finance tool with AI insights for budgeting and financial planning. Helps you give every dollar a job.', 'https://ynab.com', 'https://images.pexels.com/photos/4386476/pexels-photo-4386476.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'finance'), 'paid', '$14.99/month or $99/year.', ARRAY['budgeting','personal finance','money','savings'], 4.5, 7600, 5800, false, false, 'beginner'),

-- HR & Recruiting
('Workday', 'workday', 'AI-powered HR and finance platform', 'Workday is an enterprise HR and finance management platform with embedded AI for talent acquisition, workforce planning, and employee experience.', 'https://workday.com', 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'hr-recruiting'), 'paid', 'Enterprise pricing. Contact sales.', ARRAY['hr','enterprise','recruiting','finance'], 4.2, 4800, 3200, false, false, 'advanced'),

-- Translation
('DeepL', 'deepl', 'The world''s most accurate AI translator', 'DeepL uses neural network technology to provide translations of superior quality. Supports 31 languages and is used by millions of translators worldwide.', 'https://deepl.com', 'https://images.pexels.com/photos/4386476/pexels-photo-4386476.jpeg?w=100', (SELECT id FROM categories WHERE slug = 'translation'), 'freemium', 'Free 500,000 chars/month. Pro from $8.74/month.', ARRAY['translation','language','accuracy','documents'], 4.8, 12600, 11400, true, false, 'beginner')

ON CONFLICT (slug) DO NOTHING;